# Generated by Django 2.2.14 on 2020-07-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Год(ы)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.Poet', verbose_name='Автор(ша)')),
            ],
            options={
                'verbose_name': 'Стихотворение',
            },
        ),
    ]
