# Generated by Django 2.2.14 on 2020-07-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_auto_20200723_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poet',
            options={'ordering': ('first_name',), 'verbose_name': 'Поэт(эсса)'},
        ),
    ]
